import type {
  DashboardData,
  TraineeProfile,
  UserRole,
  VerificationQueueRow,
} from "@/lib/types";

export const courses = [
  {
    id: "course-fsd",
    name: "Full Stack Development",
    duration: "480 hrs",
    sector: "IT & Digital",
    district: "Pune",
    level: "NSQF Level 4",
  },
  {
    id: "course-cnc",
    name: "CNC Operator",
    duration: "320 hrs",
    sector: "Advanced Manufacturing",
    district: "Nashik",
    level: "NSQF Level 3",
  },
  {
    id: "course-ev",
    name: "EV Technician",
    duration: "240 hrs",
    sector: "Green Mobility",
    district: "Pune",
    level: "NSQF Level 4",
  },
  {
    id: "course-tailoring",
    name: "Advanced Tailoring",
    duration: "360 hrs",
    sector: "Apparel & Livelihoods",
    district: "Gadchiroli",
    level: "NSQF Level 3",
  },
] as const;

export const demoDashboardData: DashboardData = {
  overview: {
    total_trained: 124560,
    total_placed: 86230,
    employed_rate: 83.6,
    retention_6m_rate: 68,
    median_monthly_wage: 18500,
    province: "Maharashtra",
    updated_at: "2026-09-25T10:30:00.000Z",
    pending_verification: 2140,
    self_employed: 10840,
    training_completed: 114595,
    trend: [
      { label: "Apr", total_trained: 16240, placement_rate: 62, employed_rate: 76, retention_6m_rate: 61 },
      { label: "May", total_trained: 17480, placement_rate: 64, employed_rate: 77.5, retention_6m_rate: 62.4 },
      { label: "Jun", total_trained: 18860, placement_rate: 65.5, employed_rate: 79, retention_6m_rate: 63.8 },
      { label: "Jul", total_trained: 20120, placement_rate: 67, employed_rate: 80.2, retention_6m_rate: 65.1 },
      { label: "Aug", total_trained: 21940, placement_rate: 68.1, employed_rate: 81.8, retention_6m_rate: 66.7 },
      { label: "Sep", total_trained: 22920, placement_rate: 69, employed_rate: 83.6, retention_6m_rate: 68 },
    ],
  },
  districts: [
    {
      id: "pune",
      name: "Pune",
      trained: 28420,
      placed: 20860,
      employed_rate: 76.8,
      retention_6m_rate: 72.4,
      self_employment_rate: 12.5,
      median_wage: 23500,
      pending_verification: 420,
      top_risk_drivers: ["Contract renewal", "Shift relocation"],
      risk_level: "low",
      lat: 18.5204,
      lng: 73.8567,
    },
    {
      id: "mumbai",
      name: "Mumbai",
      trained: 36810,
      placed: 27190,
      employed_rate: 79.2,
      retention_6m_rate: 70.8,
      self_employment_rate: 10.8,
      median_wage: 26800,
      pending_verification: 610,
      top_risk_drivers: ["Gig reclassification", "Housing cost"],
      risk_level: "moderate",
      lat: 19.076,
      lng: 72.8777,
    },
    {
      id: "nashik",
      name: "Nashik",
      trained: 18240,
      placed: 12660,
      employed_rate: 69.4,
      retention_6m_rate: 64.2,
      self_employment_rate: 17.6,
      median_wage: 18900,
      pending_verification: 380,
      top_risk_drivers: ["Seasonal demand", "Wage mismatch"],
      risk_level: "moderate",
      lat: 19.9975,
      lng: 73.7898,
    },
    {
      id: "gadchiroli",
      name: "Gadchiroli",
      trained: 6980,
      placed: 4112,
      employed_rate: 58.9,
      retention_6m_rate: 55.7,
      self_employment_rate: 26.4,
      median_wage: 14200,
      pending_verification: 210,
      top_risk_drivers: ["Travel distance", "Connectivity", "Language mismatch"],
      risk_level: "high",
      lat: 19.7268,
      lng: 80.721,
    },
    {
      id: "sambhajinagar",
      name: "Chhatrapati Sambhajinagar",
      trained: 12460,
      placed: 8072,
      employed_rate: 64.8,
      retention_6m_rate: 61.9,
      self_employment_rate: 21.3,
      median_wage: 16700,
      pending_verification: 520,
      top_risk_drivers: ["Employer density", "Transport time"],
      risk_level: "moderate",
      lat: 19.8762,
      lng: 75.3433,
    },
  ],
  funnel: {
    stages: [
      { name: "Enrolled", value: 124560, percentage: 100 },
      { name: "Completed", value: 114595, percentage: 92 },
      { name: "Placed", value: 86230, percentage: 69 },
      { name: "Retained at 12 months", value: 72245, percentage: 58 },
    ],
  },
  "skill-gaps": {
    sectors: [
      {
        sector: "Priority skills",
        skills: [
          { skill: "React", supply: 76, demand: 88, gap: 12, ratio: 0.86 },
          { skill: "Node", supply: 70, demand: 84, gap: 14, ratio: 0.83 },
          { skill: "EV Diagnostics", supply: 45, demand: 92, gap: 47, ratio: 0.49 },
          { skill: "CNC Programming", supply: 58, demand: 81, gap: 23, ratio: 0.72 },
          { skill: "AWS / Docker", supply: 42, demand: 86, gap: 44, ratio: 0.49 },
        ],
      },
      {
        sector: "Advanced Manufacturing",
        skills: [
          { skill: "Industrial IoT", supply: 36, demand: 79, gap: 43, ratio: 0.46 },
          { skill: "Quality control", supply: 63, demand: 82, gap: 19, ratio: 0.77 },
          { skill: "CNC operations", supply: 58, demand: 81, gap: 23, ratio: 0.72 },
        ],
      },
      {
        sector: "Green Mobility",
        skills: [
          { skill: "EV diagnostics", supply: 45, demand: 92, gap: 47, ratio: 0.49 },
          { skill: "Battery systems", supply: 51, demand: 84, gap: 33, ratio: 0.61 },
          { skill: "Solar installation", supply: 64, demand: 86, gap: 22, ratio: 0.74 },
        ],
      },
    ],
  },
  attrition: {
    total: 12640,
    reasons: [
      { reason: "Salary Mismatch", count: 4045, percentage: 32 },
      { reason: "Unfavorable Location", count: 3034, percentage: 24 },
      { reason: "Skill Mismatch", count: 2275, percentage: 18 },
      { reason: "Family Reasons", count: 1011, percentage: 8 },
      { reason: "Other", count: 2275, percentage: 18 },
    ],
  },
  insights: {
    insights: [
      {
        id: "insight-ev-pune",
        severity: "opportunity",
        title: "EV Diagnostics demand is accelerating",
        summary:
          "EV Diagnostics demand in Pune increased by 38% in the last 6 months. Current training capacity is under-supplied by 4,500 candidates.",
        evidence: "Based on 312 verified employer demand signals and 87 certified EV technician outcomes in the current review window.",
        recommendation: "Add two EV Diagnostics batches in Pune and reserve 30% seats for candidates from Nashik and Chhatrapati Sambhajinagar.",
        metric: "+38% demand",
        sector: "Green Mobility",
        district: "Pune",
      },
      {
        id: "insight-cnc-nashik",
        severity: "watch",
        title: "CNC wage mismatch needs attention",
        summary:
          "High 3-month job attrition detected in Nashik for CNC Operators due to local wage mismatch.",
        evidence: "39 verified exits in the last 90 days; 71% cited expected pay above the reported local wage band.",
        recommendation: "Align Nashik placement wage expectations with regional manufacturing contracts and add a 60-hour advanced programming module.",
        metric: "39 early exits",
        sector: "Advanced Manufacturing",
        district: "Nashik",
      },
    ],
  },
};

export const demoTraineeProfile: TraineeProfile = {
  id: "tr-20481",
  name: "Rahul Sharma",
  internal_identifier: "ST-MH-2025-20481",
  district: "Pune",
  course: "CNC Operator – 320 hrs",
  sector: "Advanced Manufacturing",
  passport_id: "ST-PASSPORT-84F2-19AC",
  verified: true,
  training_hours: 320,
  certificate: {
    name: "NSQF Level 3 · CNC Machine Operation",
    certificate_id: "MSDB-CNC-250184",
    issued_at: "2025-08-23",
    status: "verified",
  },
  employment: {
    type: "employed",
    role: "CNC Programmer",
    employer: "ABC Manufacturing Pvt. Ltd.",
    location: "Pune, Maharashtra",
    start_date: "2025-08-18",
  },
  starting_wage: 18000,
  current_wage: 24500,
  retention: {
    month_3: 100,
    month_6: 100,
    month_12: 100,
  },
  milestones: [
    { label: "3M", status: "RETAINED", due_date: "2025-11-18" },
    { label: "6M", status: "RETAINED", due_date: "2026-02-18" },
    { label: "12M", status: "RETAINED", due_date: "2026-08-18" },
  ],
  skill_relevance: {
    score: 87,
    label: "High relevance",
    matched_skills: ["CNC Programming", "Quality Control", "Machine Safety", "Blueprint Reading"],
    role_skills: ["CNC Programming", "Quality Control", "Machine Safety", "Blueprint Reading", "Preventive Maintenance"],
  },
  confidence: {
    score: 95,
    label: "High – Verified",
  },
  risk: {
    level: "low",
    summary: "Employment, wage and skill-relevance details are recent and independently verified.",
  },
  activity: [
    {
      id: "act-rahul-1",
      title: "12-month employment verified",
      detail: "ABC Manufacturing confirmed your current role and wage band.",
      timestamp: "2026-09-18T10:20:00.000Z",
      type: "verified",
    },
    {
      id: "act-rahul-2",
      title: "Wage progression recorded",
      detail: "Monthly wage increased from ₹18,000 to ₹24,500.",
      timestamp: "2026-09-18T10:21:00.000Z",
      type: "update",
    },
    {
      id: "act-rahul-3",
      title: "CNC certification verified",
      detail: "Your 320-hour course credential is now part of the Outcome Passport.",
      timestamp: "2025-08-23T14:05:00.000Z",
      type: "credential",
    },
  ],
  updated_at: "2026-09-25T08:45:00.000Z",
};

export const sampleTraineeProfiles: TraineeProfile[] = [
  demoTraineeProfile,
  {
    ...demoTraineeProfile,
    id: "tr-20482",
    name: "Neha Kulkarni",
    internal_identifier: "ST-MH-2024-19342",
    district: "Nashik",
    course: "Advanced Tailoring – 360 hrs",
    sector: "Apparel & Livelihoods",
    passport_id: "ST-PASSPORT-17A9-22D1",
    training_hours: 360,
    certificate: {
      name: "NSQF Level 3 · Advanced Tailoring",
      certificate_id: "MSDB-TLR-240392",
      issued_at: "2024-06-17",
      status: "verified",
    },
    employment: {
      type: "self_employed",
      role: "Women’s Tailoring Studio Owner",
      employer: "Neha Stitch Studio",
      location: "Nashik, Maharashtra",
      start_date: "2025-04-08",
    },
    starting_wage: 14000,
    current_wage: 29000,
    skill_relevance: {
      score: 92,
      label: "High relevance",
      matched_skills: ["Pattern Drafting", "Industrial Sewing", "Quality Control", "Client Management"],
      role_skills: ["Pattern Drafting", "Industrial Sewing", "Quality Control", "Client Management", "Digital Payments"],
    },
    confidence: { score: 91, label: "High – Verified" },
  },
  {
    ...demoTraineeProfile,
    id: "tr-20483",
    name: "Kiran Patil",
    internal_identifier: "ST-MH-2025-18467",
    district: "Gadchiroli",
    course: "Full Stack Development – 480 hrs",
    sector: "IT & Digital",
    passport_id: "ST-PASSPORT-92C4-71B8",
    training_hours: 480,
    certificate: {
      name: "NSQF Level 4 · Web Application Development",
      certificate_id: "MSDB-FSD-250877",
      issued_at: "2025-07-02",
      status: "verified",
    },
    employment: {
      type: "apprenticeship",
      role: "Junior Web Developer Apprentice",
      employer: "Gadchiroli Digital Cooperative",
      location: "Gadchiroli, Maharashtra",
      start_date: "2026-06-01",
    },
    starting_wage: 16000,
    current_wage: 18000,
    skill_relevance: {
      score: 84,
      label: "High relevance",
      matched_skills: ["React", "JavaScript", "Git", "REST APIs"],
      role_skills: ["React", "JavaScript", "Git", "REST APIs", "Testing"],
    },
    confidence: { score: 82, label: "Medium – Proof reviewed" },
  },
  {
    ...demoTraineeProfile,
    id: "tr-20484",
    name: "Suresh Jadhav",
    internal_identifier: "ST-MH-2024-15706",
    district: "Chhatrapati Sambhajinagar",
    course: "EV Technician – 240 hrs",
    sector: "Green Mobility",
    passport_id: "ST-PASSPORT-43E8-01A6",
    training_hours: 240,
    certificate: {
      name: "NSQF Level 4 · Electric Vehicle Service",
      certificate_id: "MSDB-EVT-240611",
      issued_at: "2024-11-19",
      status: "verified",
    },
    employment: {
      type: "seeking_job",
      role: "EV Service Technician",
      employer: "Seeking opportunity",
      location: "Chhatrapati Sambhajinagar, Maharashtra",
      start_date: "",
    },
    starting_wage: 0,
    current_wage: 0,
    retention: { month_3: 0, month_6: 0, month_12: 0 },
    skill_relevance: {
      score: 81,
      label: "Good relevance",
      matched_skills: ["EV Diagnostics", "Battery Systems", "Workshop Safety"],
      role_skills: ["EV Diagnostics", "Battery Systems", "Workshop Safety", "Customer Service"],
    },
    confidence: { score: 74, label: "Medium – Self reported" },
  },
];

export const demoVerificationQueue: VerificationQueueRow[] = [
  {
    employment_id: "VER-1001",
    trainee: { name: "Rahul Sharma", internal_identifier: "ST-MH-2025-20481", district: "Pune" },
    course: { name: "CNC Operator", sector: "Advanced Manufacturing", pass_year: 2025 },
    reported: { role: "CNC Programmer", start_date: "2025-08-18", wage_band: "₹25k–₹40k", location: "Pune" },
    status: "verified",
    confidence: 95,
    submitted_at: "2026-09-24T09:18:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1002",
    trainee: { name: "Sana Pathan", internal_identifier: "ST-MH-2025-19342", district: "Nashik" },
    course: { name: "Industrial Electrical Technician", sector: "Advanced Manufacturing", pass_year: 2025 },
    reported: { role: "Electrical Technician", start_date: "2026-08-17", wage_band: "₹15k–₹25k", location: "Nashik" },
    status: "pending",
    confidence: 88,
    submitted_at: "2026-09-23T14:42:00.000Z",
    employer_confirmed: false,
  },
  {
    employment_id: "VER-1003",
    trainee: { name: "Rohan Gaikwad", internal_identifier: "ST-MH-2023-15706", district: "Chhatrapati Sambhajinagar" },
    course: { name: "CNC Operator", sector: "Advanced Manufacturing", pass_year: 2023 },
    reported: { role: "CNC Programmer", start_date: "2024-11-12", wage_band: "₹25k–₹40k", location: "Chhatrapati Sambhajinagar" },
    status: "needs_correction",
    confidence: 63,
    submitted_at: "2026-09-22T08:10:00.000Z",
    employer_confirmed: false,
  },
  {
    employment_id: "VER-1004",
    trainee: { name: "Meera Kamble", internal_identifier: "ST-MH-2024-22109", district: "Gadchiroli" },
    course: { name: "Community Health Worker", sector: "Healthcare", pass_year: 2024 },
    reported: { role: "Community Health Officer", start_date: "2025-06-02", wage_band: "₹15k–₹25k", location: "Gadchiroli" },
    status: "verified",
    confidence: 98,
    submitted_at: "2026-09-18T12:00:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1005",
    trainee: { name: "Imran Shaikh", internal_identifier: "ST-MH-2025-18467", district: "Mumbai" },
    course: { name: "Full Stack Development", sector: "IT & Digital", pass_year: 2025 },
    reported: { role: "Junior Web Developer", start_date: "2026-07-13", wage_band: "₹25k–₹40k", location: "Mumbai" },
    status: "verified",
    confidence: 92,
    submitted_at: "2026-09-17T16:28:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1006",
    trainee: { name: "Pooja Shinde", internal_identifier: "ST-MH-2024-20883", district: "Pune" },
    course: { name: "Solar Installation Technician", sector: "Green Mobility", pass_year: 2024 },
    reported: { role: "Solar Service Technician", start_date: "2025-09-09", wage_band: "₹15k–₹25k", location: "Pune" },
    status: "verified",
    confidence: 94,
    submitted_at: "2026-09-15T10:32:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1007",
    trainee: { name: "Aditya More", internal_identifier: "ST-MH-2024-17643", district: "Nashik" },
    course: { name: "CNC Operator", sector: "Advanced Manufacturing", pass_year: 2024 },
    reported: { role: "CNC Machine Operator", start_date: "2025-10-02", wage_band: "₹15k–₹25k", location: "Nashik" },
    status: "verified",
    confidence: 89,
    submitted_at: "2026-09-14T08:18:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1008",
    trainee: { name: "Shruti Pawar", internal_identifier: "ST-MH-2025-20118", district: "Pune" },
    course: { name: "Full Stack Development", sector: "IT & Digital", pass_year: 2025 },
    reported: { role: "Frontend Developer", start_date: "2026-03-16", wage_band: "₹25k–₹40k", location: "Pune" },
    status: "verified",
    confidence: 96,
    submitted_at: "2026-09-13T11:12:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1009",
    trainee: { name: "Amit Bhosale", internal_identifier: "ST-MH-2023-14872", district: "Chhatrapati Sambhajinagar" },
    course: { name: "CNC Operator", sector: "Advanced Manufacturing", pass_year: 2023 },
    reported: { role: "Production Technician", start_date: "2024-12-05", wage_band: "₹15k–₹25k", location: "Chhatrapati Sambhajinagar" },
    status: "verified",
    confidence: 90,
    submitted_at: "2026-09-12T09:45:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1010",
    trainee: { name: "Kavita Pawar", internal_identifier: "ST-MH-2025-18652", district: "Mumbai" },
    course: { name: "EV Technician", sector: "Green Mobility", pass_year: 2025 },
    reported: { role: "EV Service Advisor", start_date: "2026-05-11", wage_band: "₹15k–₹25k", location: "Mumbai" },
    status: "verified",
    confidence: 87,
    submitted_at: "2026-09-11T15:22:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1011",
    trainee: { name: "Vikram Salunke", internal_identifier: "ST-MH-2024-22580", district: "Gadchiroli" },
    course: { name: "Advanced Tailoring", sector: "Apparel & Livelihoods", pass_year: 2024 },
    reported: { role: "Production Supervisor", start_date: "2025-08-19", wage_band: "₹15k–₹25k", location: "Gadchiroli" },
    status: "verified",
    confidence: 91,
    submitted_at: "2026-09-10T12:35:00.000Z",
    employer_confirmed: true,
  },
  {
    employment_id: "VER-1012",
    trainee: { name: "Rutuja Deshmukh", internal_identifier: "ST-MH-2025-21109", district: "Pune" },
    course: { name: "Full Stack Development", sector: "IT & Digital", pass_year: 2025 },
    reported: { role: "Software Support Associate", start_date: "2026-08-24", wage_band: "₹15k–₹25k", location: "Pune" },
    status: "verified",
    confidence: 85,
    submitted_at: "2026-09-09T10:18:00.000Z",
    employer_confirmed: true,
  },
];

export const demoUsers: Record<UserRole, { name: string; email: string; organization?: string }> = {
  trainee: {
    name: "Rahul Sharma",
    email: "trainee@skilltrace.in",
  },
  employer: {
    name: "Neha Kulkarni",
    email: "employer@skilltrace.in",
    organization: "ABC Manufacturing Pvt. Ltd.",
  },
  admin: {
    name: "Dr. Kavita Rao",
    email: "admin@skilltrace.in",
    organization: "Maharashtra Skill Development",
  },
};

export const formatIndianNumber = (value: number) =>
  new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(value);

export const formatCurrency = (value: number) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
